(function(){'use strict';function initializeFramework(){function setupSidebar(){const sidebar=document.querySelector('.sidebar');const sidebarOverlay=document.querySelector('.sidebar-overlay');const mobileToggleBtn=document.querySelector('.site-nav .sidebar-toggle-btn');const desktopToggleBtn=document.querySelector('.sidebar-header .sidebar-toggle-btn');if(mobileToggleBtn){mobileToggleBtn.addEventListener('click',()=>{sidebar.classList.toggle('show');if(sidebarOverlay){sidebarOverlay.classList.toggle('show')}})}
if(sidebarOverlay){sidebarOverlay.addEventListener('click',()=>{sidebar.classList.remove('show');sidebarOverlay.classList.remove('show')})}
if(desktopToggleBtn){desktopToggleBtn.addEventListener('click',()=>{sidebar.classList.toggle('collapsed')})}}
function setupModals(){const modalToggles=document.querySelectorAll('[data-toggle="modal"]');modalToggles.forEach(toggle=>{toggle.addEventListener('click',()=>{const targetSelector=toggle.getAttribute('data-target');const modal=document.querySelector(targetSelector);if(modal){modal.classList.add('show')}})});const closeModal=(modal)=>{if(!modal)return;modal.classList.add('is-closing');modal.addEventListener('animationend',()=>{modal.classList.remove('show');modal.classList.remove('is-closing')},{once:!0})};document.querySelectorAll('.modal').forEach(modal=>{const backdrop=modal.querySelector('.modal-backdrop');const closeButtons=modal.querySelectorAll('.modal-close-btn, [data-dismiss="modal"]');if(backdrop){backdrop.addEventListener('click',()=>closeModal(modal))}
closeButtons.forEach(btn=>{btn.addEventListener('click',()=>closeModal(modal))})})}
function setupTabs(){const tabLinks=document.querySelectorAll('.tab-link');tabLinks.forEach(link=>{link.addEventListener('click',(e)=>{e.preventDefault();const targetPaneId=link.getAttribute('href');const targetPane=document.querySelector(targetPaneId);if(!targetPane){console.warn(`Tab pane ${targetPaneId} non trovato.`);return}
const tabsNav=link.closest('.tabs-nav');const tabContentContainer=targetPane.closest('.tabs-content');tabsNav.querySelectorAll('.tab-link').forEach(tl=>{tl.classList.remove('active')});if(tabContentContainer){Array.from(tabContentContainer.children).forEach(pane=>{if(pane.classList.contains('tab-pane')){pane.classList.remove('active')}})}else{Array.from(targetPane.parentNode.children).forEach(pane=>{if(pane.classList.contains('tab-pane')){pane.classList.remove('active')}})}
link.classList.add('active');targetPane.classList.add('active')})});document.querySelectorAll('.tabs-nav').forEach(nav=>{const firstLink=nav.querySelector('.tab-link.active');if(firstLink){const targetPaneId=firstLink.getAttribute('href');const targetPane=document.querySelector(targetPaneId);if(targetPane){targetPane.classList.add('active')}}else{const first=nav.querySelector('.tab-link');if(first){first.classList.add('active');const targetPaneId=first.getAttribute('href');const targetPane=document.querySelector(targetPaneId);if(targetPane){targetPane.classList.add('active')}}}});document.querySelectorAll('.tab-pane:not(.active)').forEach(pane=>{pane.classList.remove('active')})}
function setupDropdowns(){const dropdownToggles=document.querySelectorAll('[data-toggle="dropdown"]');dropdownToggles.forEach(toggle=>{toggle.addEventListener('click',(e)=>{e.preventDefault();e.stopPropagation();const menu=toggle.closest('.dropdown').querySelector('.dropdown-menu');closeAllDropdowns(menu);if(menu){menu.classList.toggle('show')}})});window.addEventListener('click',(e)=>{if(!e.target.matches('[data-toggle="dropdown"]')){closeAllDropdowns()}});function closeAllDropdowns(excludeMenu=null){document.querySelectorAll('.dropdown-menu.show').forEach(menu=>{if(menu!==excludeMenu){menu.classList.remove('show')}})}}
setupSidebar();setupModals();setupTabs();setupDropdowns()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initializeFramework)}else{initializeFramework()}})()